name: Type Hint Test

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  type-hint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Test with mypy
        run: |
          pipenv run mypy src
